djcrm/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from leads.views import LandingPageView
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from leads.views import SignUpView
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('sign-up/', SignUpView.as_view(), name='sign-up'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confir'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete')
]


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

leads/urls.py
from django.urls import path
from .views import (
    AssignedAgentView, CategoryListView, CategoryDetailView,
    CategoryCreateView, CategoryUpdateView, CategoryDeleteView,
    LeadListView, LeadDetailView, LeadCreateView,
    LeadUpdateView, LeadDeleteView, LeadCategoryUpdateView
)

app_name = 'leads'

urlpatterns = [
    path('', LeadListView.as_view(), name='lead-list'),
    path('create/', LeadCreateView.as_view(), name='lead-create'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead-detail'),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='lead-delete'),
    path('<int:pk>/assign-agent/', AssignedAgentView.as_view(), name='assign-agent'),
    path('<int:pk>/category', LeadCategoryUpdateView.as_view(), name='lead-category-update'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('create-category/', CategoryCreateView.as_view(), name='category-create'),
    path('categories/<int:pk>', CategoryDetailView.as_view(), name='category-detail'),
    path('categories/<int:pk>/update', CategoryUpdateView.as_view(), name='category-update'),
    path('categories/<int:pk>/delete', CategoryDeleteView.as_view(), name='category-delete'),

]

templates/category/category_create.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'leads:category-list' %}">
        Go back to categories
    </a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Create a new category</h1>
    </div>
    
    <form class='mt-5' method="POST">
        {% csrf_token  %}
        {{ form|crispy }}
        <button class='w-full bg-blue-500 text-white hover:bg-blue-600 px-3 py-2 rounded-md' type="submit">
            Submit
        </button>
    </form>
</div>
{% endblock content %}

templates/category/category_delete.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'leads:category-list' %}">
        Go back to categories
    </a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Are you sure you want to delete {{ object.name }}?</h1>
    </div>
    
    <form class='mt-5' method="POST">
        {% csrf_token  %}
        {{ form|crispy }}
        <button class='w-full bg-blue-500 text-white hover:bg-blue-600 px-3 py-2 rounded-md' type="submit">
            Submit
        </button>
    </form>
</div>
{% endblock content %}

templates/category/category_detail.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">
            {{ category.name }}
        </h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
            These are leads under this caterogy
        </p> 
        <a href="{% url 'leads:category-update' category.pk %}" class="hover:text-blue-500">Update</a>
        <a href="{% url 'leads:category-delete' category.pk %}" class="hover:text-blue-500">Delete</a>
      </div>
      <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">
                  First Name
                </th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
                  Last Name
                </th>
            </tr>
          </thead>
          <tbody>
            {% for lead in category.leads.all %}
            <tr>
                <td class="px-4 py-3">
                    <a class="hover:text-blue-500" href="{% url 'leads:lead-detail' lead.pk %}">{{ lead.first_name }}</a>
                </td>
                <td class="px-4 py-3">{{ lead.last_name }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section>

{% endblock content %}

templates/category/category_list.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Categories</h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
            These categories segment the leads
        </p>
        <a href="{% url 'leads:category-create' %}" class="hover:text-blue-500">Create a category</a>
      </div>
      <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Name</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Lead Count</th>
            </tr>
          </thead>
          <tbody>
            <tr>
                <td class="px-4 py-3">Unassigned</td>
                <td class="px-4 py-3">{{ unassigned_lead_count }}</td>
            </tr>
            {% for category in category_list %}
            <tr>
                <td class="px-4 py-3">
                    <a class="hover:text-blue-500" href="{% url 'leads:category-detail' category.pk %}">{{ category.name }}</a>
                </td>
                <td class="px-4 py-3">{{ lead_count }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section>

{% endblock content %}

templates/category/category_update.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'leads:category-list' %}">
        Go back to categories
    </a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Update {{object.name}} </h1>
    </div>
    
    <form class='mt-5' method="POST">
        {% csrf_token  %}
        {{ form|crispy }}
        <button class='w-full bg-blue-500 text-white hover:bg-blue-600 px-3 py-2 rounded-md' type="submit">
            Submit
        </button>
    </form>
</div>
{% endblock content %}